= Haxelock

**NOTE** this is still unstable, not all planned features are implemented yet.

== Intent

I decided to create this tool because I didn't find anything out there that I liked for managing library versions in haxelib. I didn't want something overly complicated and I wanted something small and dependency free.

So sorry for another build manager / package manager / library tool, but I feel that this one has value.

== Usage

**Haxelock** calls other apps and scripts (**Haxe, **Haxelib**, **Git**) when running. These should be available in the path.

If you install it in your path you can use.

```
haxelock build.hxml
```

Or if you prefer to use in in haxelib you can run

```
haxelib install haxelock
haxelib run haxelock build.hxml
```

(currently not on haxelib)

== What Haxelock does

*Haxelock* allows you to track and manage what verions of what libraries are used to build your projects.

* keeps track of project library versions
* uses haxelib, git to change / update versions
* automatically checks on an "upgrade" if the project still builds

It currently supports

* haxelib libraries

Git and Dev libraries will be implemented next.

=== Give Me More Details

**Haxelock** is a simple executable which calls *haxe*, *haxelib*, and *git*.

. Checks if there is a `haxelib.lock` file in the project root.
** if it exists, it will check the libraries in that file against what is current in haxelib
** it will attempt to change the versions to those in the file, and will let you know if it fails
*** if it fails then it will stop the build process.
 
. it will then build the project
** if the project fails, it will echo the build failure

=== Commands

These are the currently implemented commands and their function

* `haxelock <file.hxml>` : builds the passed hxml file with the tracked versions.
* `haxelock upgrade <library, library>` : used to update a library(s) and test the project to ensure that change in library version doesn't break the project.
* `haxelock list` : lists all tracked libraries and their version.
* `haxelock lock <file.hxml>` : creates a lockfile from the given hxml file, can also be made to use all .hxml files if desired.
* `haxelock set <library> <version>` set a specific library to a specific version.
* `haxelock help` list more information about haxelock and haxelock commands.

Some of these commands have switches to modify behavior, refer the to the specific help section to see what to do i.e. `haxelock help upgrade`